export const GRID_HALF = 52;

export const CITY_ORDER = ['bos', 'nyc', 'phl', 'dc', 'atl', 'mia', 'chicago', 'dal', 'lax', 'sf', 'sea'];

export const CITIES = {
  chicago: {
    id: 'chicago',
    name: 'Chicago',
    title: 'Chicago — Airspace',
    href: '/',
    anchor: { x: -8, z: 2, origin: { lat: 41.9786, lon: -87.9048 } },
    half: GRID_HALF,
    label: 'Chicago',
    labelAt: [8, 16, -14],
    camera: { position: [10, 32, 88], target: [24, 3, 16] },
    water: 'east',
    sample: 'traffic-sample.json',
  },
  lax: {
    id: 'lax',
    name: 'Los Angeles',
    title: 'Los Angeles — Airspace',
    href: '/lax.html',
    anchor: { x: -8, z: 2, origin: { lat: 33.9425, lon: -118.4081 } },
    half: 100,
    divisions: 50,
    maxDistance: 280,
    label: 'Los Angeles',
    labelAt: [-18, 18, -18],
    camera: { position: [20, 40, 92], target: [12, 3, 2] },
    water: 'west',
    sample: 'traffic-sample-lax.json',
  },
  phl: {
    id: 'phl',
    name: 'Philadelphia',
    title: 'Philadelphia — Airspace',
    href: '/phl.html',
    anchor: { x: 0, z: 0, origin: { lat: 39.91, lon: -75.18 } },
    half: 64,
    divisions: 32,
    maxDistance: 260,
    label: 'Philadelphia',
    labelAt: [-36, 22, -48],
    camera: { position: [8, 46, 100], target: [-2, 2, -6] },
    water: null,
    sample: 'traffic-sample-phl.json',
  },
  dc: {
    id: 'dc',
    name: 'Washington',
    title: 'Washington — Airspace',
    href: '/dc.html',
    anchor: { x: 0, z: 0, origin: { lat: 38.9, lon: -77.04 } },
    half: 96,
    divisions: 48,
    maxDistance: 280,
    label: 'Washington',
    labelAt: [-20, 20, -78],
    camera: { position: [8, 52, 108], target: [2, 2, -4] },
    water: null,
    sample: 'traffic-sample-dc.json',
  },
  sf: {
    id: 'sf',
    name: 'San Francisco',
    title: 'San Francisco — Airspace',
    href: '/sf.html',
    anchor: { x: 0, z: 0, origin: { lat: 37.74, lon: -122.38 } },
    half: 52,
    divisions: 26,
    maxDistance: 240,
    label: 'San Francisco',
    labelAt: [-40, 22, -28],
    camera: { position: [6, 46, 98], target: [-4, 2, -10] },
    water: null,
    sample: 'traffic-sample-sf.json',
  },
  bos: {
    id: 'bos',
    name: 'Boston',
    title: 'Boston — Airspace',
    href: '/bos.html',
    anchor: { x: 0, z: 0, origin: { lat: 42.355, lon: -71.085 } },
    half: 18,
    divisions: 18,
    maxDistance: 160,
    label: 'Boston',
    labelScale: 0.34,
    labelAt: [2, 8, -6],
    camera: { position: [2, 22, 40], target: [3, 1, -1] },
    water: null,
    sample: 'traffic-sample-bos.json',
  },
  atl: {
    id: 'atl',
    name: 'Atlanta',
    title: 'Atlanta — Airspace',
    href: '/atl.html',
    anchor: { x: 0, z: 0, origin: { lat: 33.72, lon: -84.4 } },
    half: 52,
    divisions: 26,
    maxDistance: 240,
    label: 'Atlanta',
    labelAt: [-12, 22, -36],
    camera: { position: [4, 46, 98], target: [0, 2, -6] },
    water: null,
    sample: 'traffic-sample-atl.json',
  },
  mia: {
    id: 'mia',
    name: 'Miami',
    title: 'Miami — Airspace',
    href: '/mia.html',
    anchor: { x: 0, z: 0, origin: { lat: 25.78, lon: -80.22 } },
    half: 40,
    divisions: 20,
    maxDistance: 220,
    label: 'Miami',
    labelAt: [-22, 18, -16],
    camera: { position: [-4, 38, 76], target: [6, 2, -2] },
    water: null,
    sample: 'traffic-sample-mia.json',
  },
  dal: {
    id: 'dal',
    name: 'Dallas',
    title: 'Dallas — Airspace',
    href: '/dal.html',
    anchor: { x: 0, z: 0, origin: { lat: 32.84, lon: -97 } },
    half: 72,
    divisions: 36,
    maxDistance: 280,
    label: 'Dallas',
    labelAt: [6, 24, -48],
    camera: { position: [8, 52, 118], target: [10, 2, 2] },
    water: null,
    sample: 'traffic-sample-dal.json',
  },
  sea: {
    id: 'sea',
    name: 'Seattle',
    title: 'Seattle — Airspace',
    href: '/sea.html',
    anchor: { x: 0, z: 0, origin: { lat: 47.54, lon: -122.32 } },
    half: 44,
    divisions: 22,
    maxDistance: 220,
    label: 'Seattle',
    labelAt: [6, 22, -32],
    camera: { position: [2, 42, 88], target: [0, 2, -8] },
    water: null,
    sample: 'traffic-sample-sea.json',
  },
  nyc: {
    id: 'nyc',
    name: 'New York',
    title: 'New York — Airspace',
    href: '/nyc.html',
    anchor: { x: 0, z: 0, origin: { lat: 40.7, lon: -74 } },
    half: 48,
    divisions: 24,
    maxDistance: 240,
    label: 'New York',
    labelAt: [-18, 17, -26],
    camera: { position: [8, 46, 102], target: [6, 2, -1] },
    water: null,
    sample: 'traffic-sample-nyc.json',
  },
};

export function cityById(id) {
  return CITIES[id] || CITIES.chicago;
}
